### ISSUE TITLE
Usage instructions? can't use

### ISSUE THREAD

**Issue by Madd0g** [kanru/rage-wasm#2]
hey, trying to use this library and having problems

I tried running with node v16 and tried from an mjs file:

tried import:

```ts
import rage from '@kanru/rage-wasm';
```

got this:
```
Error: Cannot find module '@kanru/rage-wasm'
```

tried `require`
```js
const rage = require('@kanru/rage-wasm');
```
and tried this in typescript

```ts
import rage from '@kanru/rage-wasm/dist/index.js';
```

got this:

```
export { decrypt_with_user_passphrase$1 as decrypt_with_user_passphrase, decrypt_with_x25519$1 as decrypt_with_x25519, encrypt_with_user_passphrase$1 as encrypt_with_user_passphrase, encrypt_with_x25519$1 as encrypt_with_x25519, keygen$1 as keygen };
^^^^^^
SyntaxError: Unexpected token 'export'
```

I managed to configure typescript to compile the index.js file (not sure exactly which combination of tsconfig settings led to this), after which I got this neat error:

```
TypeError: Cannot assign to read only property 'keygen' of object '[object Object]'
```

also, I'm assuming the `wasm-pack build` step is for development, not for end users? I don't see that binary anywhere int the npm lib.

Thanks

**Comment by dol** [comment]
@Madd0g I had the same question. I ended up cloning this repo (not the `npm install` way) and built the wasm integration with `wasm-pack build --release --target web`.

I then created an index.html file in the root folder:

```html
<html>

<head>
  <meta content="text/html;charset=utf-8" http-equiv="Content-Type" />
</head>

<body>
  Encrypt your secrets:
  <input name="password" type="password" id="password" />
  <input type="submit" id="submit" value="Submit" />
  <p>
    <textarea name="result" type="textarea" id="result" rows="10" cols="68"></textarea>
  </p>
  <script type="module">
    import init, { encrypt_with_x25519 } from './pkg/rage_wasm.js';

    function encrypt_password() {
      const public_key = '<agepublickey>'
      const password = new TextEncoder().encode(document.getElementById('password').value);
      const result = new TextDecoder().decode(encrypt_with_x25519(public_key, password, true));
      document.getElementById('result').value = result
    }

    init().then(() => {
      document.getElementById('result').value = ''
      document.getElementById('submit').onclick = encrypt_password;
    });

  </script>
  <script type=text/javascript>
  </script>
</body>

</html>
```

Serving the index.html with the help of `python -m SimpleHTTPServer 8000`

**Comment by Madd0g** [comment]
@dol - thanks, I will try

**Comment by kanru** [comment]
Hi @Madd0g thanks for opening this issue. I added an example here https://github.com/kanru/rage-wasm/tree/main/examples/parcel

Currently the published version on npm only provides the es6 module without default exports so each function needs to be imported like

```js
import keygen from '@kanru/rage-wasm';
```

Or import all under a new name

```js
import * as rage from '@kanru/rage-wasm';
```

If your environment is not ES6 module native then a bundler or transpiler will be required.

I think the current typescript type is not accurate, I'll update it in later version.
